project:
  type: website
  preview:
    host: 0.0.0.0
    port: 4000

website:
  title: "Dupsifter Documentation"
  description: "Documentation site for dupsifter, a WGBS/WGS duplicate marking tool"
  page-footer:
    left: "Copyright 2024, The Shen Lab at Van Andel Institute"
    right:
      - icon: github
        href: https://github.com/huishenlab/dupsifter
  sidebar:
    style: "docked"
    background: "#E3E3E3"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - href: install.qmd
        text: Download/Install
      - href: usage.qmd
        text: Usage
      - href: methodology.qmd
        text: Methodology
      - href: examples.qmd
        text: Examples
      - href: releases.qmd
        text: Releases
    tools:
      - icon: github
        menu:
          - text: Source Code
            url: https://github.com/huishenlab/dupsifter
          - text: Report a Bug
            url: https://github.com/huishenlab/dupsifter/issues

format:
  html:
    theme: flatly
    highlight-style: solarized
    css: styles.css
    toc: true
    code-copy: true
    code-block-border-left: "#000000"
    code-block-bg: "#F3F3F3"



